stages:          # List of stages for jobs, and their order of execution
  - build

build-on-linux-job:
  image: archlinux:latest
  stage: build
  script:
    - pacman -Sy --noconfirm
    - pacman -S qt6-base qt6-charts qt6-connectivity qt6-serialport --noconfirm
    - qmake
    - make
  artifacts:
    paths:
      - /builds/ambition-echo/uestctools/UestcTools