name: Build
on: push

jobs:
  #Linux编译
  Build-Linux:
    #运行平台
    name: Build on Linux
    runs-on: ubuntu-latest
    #编译步骤
    steps:
      #1安装Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          arch: 'gcc_64'
          modules: qtcharts
          target: 'desktop'
      #2拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      #3编译构建
      - name: Build
        run: |
          qmake
          make
      #4打包成zip
      - name: To zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'Heart'
          filename: 'Heart_Linux.zip'
      #5上传artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Heart_Linux.zip
          path: /home/runner/work/Heart/Heart/Heart
          if-no-files-found: error
      #6发布release
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /home/runner/work/Heart/Heart/Heart_Linux.zip
          tag: ${{ github.ref }}
          overwrite: true
  #windows编译
  Build-Windows:
    #运行平台
    name: Build on Windows
    runs-on: windows-2019
    #编译步骤
    steps:
      #1安装Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          arch: 'win64_msvc2019_64'
          modules: qtcharts
          target: 'desktop'
      #2拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      #3编译构建
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake
      #4打包部署
      - name: package
        run: |
          md D:/a/Heart/Heart/build
          copy D:/a/Heart/Heart/release/Heart.exe D:/a/Heart/Heart/build
          windeployqt.exe D:/a/Heart/Heart/build/Heart.exe
      #5打包成zip
      - name: To zip
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'build'
          filename: 'Heart_Windows.zip'
      #6上传artifact
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Heart_Windows.zip
          path: D:/a/Heart/Heart/build
          if-no-files-found: error
      #7发布release
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: Heart_Windows.zip
          tag: ${{ github.ref }}
          overwrite: true