name: Linux
on: push

jobs:
  #编译
  build:
    #基本信息
    name: Build
    runs-on: ubuntu-latest

    steps:
      #安装Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          arch: 'gcc_64'
          modules: qtcharts
          target: 'desktop'
      #拉取仓库
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      #编译构建
      - name: build ubuntu
        run: |
          qmake
          make
      #上传artifact
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: Heart
          path: /home/runner/work/Heart/Heart
          if-no-files-found: error