name: MacOS
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: macos-10.15

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'mac'
          arch: 'clang_64'
          modules: qtcharts
          target: 'desktop'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build macos
        run: |
          qmake
          make
          pwd
          ls
      # 打包
      - name: package
        run: |
          # 拷贝依赖
          cd bin/release
          ls
          macdeployqt bin/release/Heart.app -qmldir=. -verbose=1 -dmg
      # 上传artifacts          
      - uses: actions/upload-artifact@v2
        with:
          name: Heart_MacOS
          path: bin/release/Heart.app